baseurl = "/"
languageCode = "en-us"
title = "A minimal Hugo website"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"
enableEmoji  = true
# googleAnalytics = "UA-162188416-1"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "主页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "RSS"
    url = "/index.xml"

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [Yuquan Xu](https://xyq.netlify.com) 2019 -- 2020 | [iBIDS](http://ibids.cn) "
